/* Auth */
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/* Classroom */
export const GET_CLASSROOM = "GET_CLASSROOM";
export const GET_CLASSROOM_SUCCESS = "GET_CLASSROOM_SUCCESS";
export const GET_CLASSROOM_FAILURE = "GET_CLASSROOM_FAILURE";

/* Select Class */
export const SELECT_CLASS = "SELECT_CLASS";

/* Get Class.Student */
export const GET_CLASS_STUDENT = "GET_CLASS_STUDENT";
export const GET_CLASS_STUDENT_SUCCESS = "GET_CLASS_STUDENT_SUCCESS";
export const GET_CLASS_STUDENT_FAILURE = "GET_CLASS_STUDENT_FAILURE";

/* Notice */
export const GET_NOTICE = "GET_NOTICE";
export const GET_NOTICE_SUCCESS = "GET_NOTICE_SUCCESS";
export const GET_NOTICE_FAILURE = "GET_NOTICE_FAILURE";

export const POST_NOTICE = "POST_NOTICE";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAILURE = "POST_NOTICE_FAILURE";

/* Project (Kanbanboard) */
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const POST_PROJECT = "POST_PROJECT";
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE";

export const PUT_PROJECT = "PUT_PROJECT";
export const PUT_PROJECT_SUCCESS = "PUT_PROJECT_SUCCESS";
export const PUT_PROJECT_FAILURE = "PUT_PROJECT_FAILURE";

export const GET_STANDBY_PROJECT = "GET_STANDBY_PROJECT";
export const GET_STANDBY_PROJECT_SUCCESS = "GET_STANDBY_PROJECT_SUCCESS";
export const GET_STANDBY_PROJECT_FAILURE = "GET_STANDBY_PROJECT_FAILURE";
