/* Auth */
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/* Classroom */
export const GET_CLASSROOM = "GET_CLASSROOM";
export const GET_CLASSROOM_SUCCESS = "GET_CLASSROOM_SUCCESS";
export const GET_CLASSROOM_FAILURE = "GET_CLASSROOM_FAILURE";

/* Select Class */
export const SELECT_CLASS = "SELECT_CLASS";

/* Notice */
export const POST_NOTICE = "POST_NOTICE";
export const POST_NOTICE_SUCCESS = "POST_NOTICE_SUCCESS";
export const POST_NOTICE_FAILURE = "POST_NOTICE_FAILURE";
